### PR TITLE
add collet holder openscad design

### PR DESCRIPTION
**Pull request by bburdette**

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
I like it, but two questions/concerns:
1. Don't we have duplicates of some collet sizes?
1. Doesn't this hold the collets with the "nose" down, so you can't see the size?  Or will they fit with the nose up?

**Comment by bburdette** [comment]
There's only one size with a duplicate.  That one can just hang out in the back.  They do go with the hole down, but there's a size chart, so its quick to get one if you know the size.  There's a picture on slack.

**Comment by SebKuzminsky** [comment]
And i just noticed that you already printed one and it's installed and in use.  Neat, thanks for doing that!

**Comment by bburdette** [comment]
Machined on the shotbot itself!  Out of some kind of plastic that was laying around.  Thx for the merge.

**Pull request merged**
